---
- hosts: web2
  tasks:
    - name: install packages 
      yum: 
        name: httpd, firewalld
        state: present
    - name: service enabled/started 
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - httpd
        - firewalld

    - name: Change Apache port
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: "Listen 80"
        replace: "Listen 8082"

    - name: Restart Apache service
      service:
        name: httpd
        state: restarted
   
    - name: firewall rule
      firewalld:
        port: 8082/tcp
        state: enabled
        zone: public
        permanent: yes
        immediate: yes


##We have a playbook ~/playbooks/web2-config.yml, it has some existing code to change apache’s default port 80 to port 8082 as we want to run Apache on port 8082 on web2 node. Make some changes as given below before running the playbook.



##A. Add an entry in ~/playbooks/inventory for web2 node, IP address of web2 node is 172.20.1.101 and ssh password and username are same as of web1 (username = root and password = Passw0rd).

##B. Update web2-config.yml to install httpd before updating its port in config, also start/enable its service.

##C. Install firewalld package and start/enable its service.

#D. As now Apache will listen on port 8082 so edit the playbook to add firewall rule in public zone so that Apache can allow all incoming traffic.        