---
- hosts: node00
  tasks: 
  - cron:
      name: Free Memory Check
      minute: "0"
      hour: "*/2" 
      job: "sh /root/free.sh"

# Readme.md
# We have a script /root/free.sh on node00 that is used to check the free system memory. We would like to create a cron Free Memory Check to execute this script after every 2 hour (i.e 12am, 2am, 4am etc), the command to execute the script is sh /root/free.sh and schedule should be 0 */2 * * *      